name: slidable_bar
description: A Flutter package to show side bar and hide it.
version: 1.0.0
issue_tracker: https://github.com/mahmoud-haj-ali/slidable_bar/issues
homepage: https://github.com/mahmoud-haj-ali/slidable_bar

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

